Header header

uint8 AIRS_Light_Left           
uint8 AIRS_Light_Right          
uint8 AIRS_Driver_Light_Forward 
uint8 AIRS_Driver_Light_Backward
uint8 AIRS_Wiper_Spary          
uint8 AIRS_Wiper_Intermittent   
uint8 AIRS_Wiper_Fast           
uint8 AIRS_E_Stop_Triggered     
uint8 AIRS_Neutral              
uint8 AIRS_Horn                 
uint8 AIRS_Drive_D              
uint8 AIRS_Drive_R              
uint8 AIRS_Drive_Packing_N      
uint8 AIRS_Heart_bit            